name: Ejercicio1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

 # schedule:
  #  - cron:  '0 9 * * *'
   

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: AUTOMATIZACIÓN
      run: |
          echo "ola"
          #python -m pip install --upgrade pip
          #pip install -r requirements.txt
          #python primer.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        # commit_user_email: gholley42@gmail.com
        # commit_author: DataIntelligence BOT <gholley42@gmail.com>

        commit_user_email: clentebanks0@gmail.com
        commit_author: DataIntelligence BOT <clentebanks0@gmail.com>

        push_options: '--force'


   
